steps:
# build Docker image
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-flask-app', '.']
# push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcp-flask-app']
# deploy container image on GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=deployment.yaml
  - --image=gcr.io/$PROJECT_ID/gcp-flask-app
  - --location=us-central1-c
  - --cluster=cluster-1
  - --namespace=default