# Set BUILD_DEPLOY_NAME based on branch name (assuming branch name is passed as argument)

steps:
# build Docker image
- name: 'docker'
  env:
    - 'BUILD_DEPLOY_NAME=prod'
  script: 'BUILD_DEPLOY_NAME=$(if [[ "${TRIGGER_BRANCH}" != "main" ]]; then echo "${TRIGGER_BRANCH}"; fi)'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${BUILD_DEPLOY_NAME}/gcp-flask-app', '.']
  dir: 'app'

# push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/${BUILD_DEPLOY_NAME}/gcp-flask-app']
# deploy container image on GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=kubernetes/flask-app-${BUILD_DEPLOY_NAME}.yaml
  - --image=gcr.io/${PROJECT_ID}/${BUILD_DEPLOY_NAME}/gcp-flask-app
  - --location=us-central1-c
  - --cluster=cluster-1
  - --namespace=${BUILD_DEPLOY_NAME}