apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application
spec:
  replicas: 2
  selector:
    matchLables:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: flask-container
        image: gcr.io/voltaic-circuit-420516/gcp-docker:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"

