apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application
  labels: 
    tier: backend-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: flask-container
        image: gcr.io/voltaic-circuit-420516/gcp-docker:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
  labels: 
    tier: backend-flask
spec:
  selector:
    app: gcp
  ports:
  - port: 80
    targetPort: 5000
  type: "LoadBalancer"
