apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application-qa
  labels: 
    app: gcp
    tier: backend-flask-qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp
      tier: backend-flask-qa
  template:
    metadata:
      labels:
        app: gcp
        tier: backend-flask-qa
    spec:
      containers:
      - name: flask-container-qa
        image: gcr.io/voltaic-circuit-420516/qa/gcp-flask-app:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: FLASK_ENV
            value: "qa"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc-qa
  labels:
    app: gcp
    tier: backend-flask-qa
spec:
  selector:
    app: gcp
    tier: backend-flask-qa
  ports:
  - port: 80
    targetPort: 5000
  type: "LoadBalancer"
